model_type: HPGDMPModel
scale: 1
num_gpu: 1
manual_seed: 0


datasets:
  train:
    name: General_Image_Train
    type: PairedImageDataset
    dataroot_gt: /data/root/dataset/haze_dataset/ITS_single/gt
    io_backend:
      type: disk
 
    gt_size: 256
    use_resize_crop: true
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    batch_size_per_gpu: &bsz 6
    num_worker_per_gpu: *bsz 
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: *bsz

  val:
    name: General_Image_Valid
    type: PairedImageDataset
    dataroot_gt: /data/root/FeMaSR-main/val
    dataroot_lq: /data/root/FeMaSR-main/val
    io_backend:
      type: disk

# network structures
network_g:
  type: HPGDMPNet
  gt_resolution: 256
  norm_type: 'gn'
  act_type: 'silu'
  use_semantic_loss: False
  codebook_params:
    - [32, 1024, 512]

  LQ_stage: false 
  use_quantize: true
  
network_d:
  type: UNetDiscriminatorSN 
  num_in_ch: 3


# path
path:
  pretrain_network_g: /data/root/CVPR23Derain/FeMaSR-main/net_g_250000.pth
  pretrain_network_d: /data/root/CVPR23Derain/FeMaSR-main/net_d_250000.pth

  strict_load: False
  resume_state: ~
  training_states: ~

#  pretrain_network_g: ~
#  pretrain_network_d: ~
  ignore_resume_networks: None
# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [5000, 10000, 15000, 20000, 25000, 30000, 35000]
    gamma: 1

  total_iter: 50000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  detail_weight:
    hog: 0.1
    low_frequency: 0.1
    grad: 0.1

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: !!float 1.0

  gan_opt:
    type: GANLoss
    gan_type: hinge
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 0.1

  codebook_opt:
    loss_weight: 1.0

  semantic_opt:
    loss_weight: 0.1

  net_d_iters: 1
  net_d_init_iters: !!float 0

# validation settings·
val:
  val_freq: !!float 5e3
  save_img: false

  key_metric: lpips
  metrics:
    psnr:
      type: psnr
      crop_border: 4
      test_y_channel: true
      color_space: ycbcr
    ssim:
      type: ssim
      crop_border: 4
      test_y_channel: true
      color_space: ycbcr
    lpips:
      type: lpips
      better: lower

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e9
  save_latest_freq: !!float 5e3
  show_tf_imgs_freq: !!float 1e3
  use_tb_logger: true
